[package]
name = "echoip"
version = "0.1.0"
authors = ["Michael Laccetti <michael@laccetti.com>"]
edition = "2018"
include = ["/Cargo.toml","/src/**/*.rs", "/README.md", "/LICENSE"]

[[bin]]
name = "echoip"
path = "src/main.rs"

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
maxminddb = "0.21.0"
rocket = "0.5.0-rc.1"
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["handlebars"] }
serde = "=1.0.130"
serde_derive = "1.0.130"
serde_json = "=1.0.67"
thiserror = "=1.0.29"
